version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs_db
    ports:
      - "3306:3306"
